FROM ubuntu:16.04
ENV HOME /home

RUN apt-get update && apt-get install -y openssh-client \
    bash 
EXPOSE 22

WORKDIR ${HOME}
COPY ./id_rsa /root/.ssh/id_rsa
RUN chmod 700 /root/.ssh/
RUN chmod 700 /root/.ssh/id_rsa

RUN echo "PasswordAuthentication no" >> /etc/ssh/sshd_config
RUN echo "StrictHostKeyChecking no" >> /etc/ssh/ssh_config
RUN echo "UserKnownHostsFile /dev/null" >> /root/.ssh/config
CMD eval $(ssh-agent -s) && ssh-add /root/.ssh/id_rsa && ssh -o StrictHostKeyChecking=no nginx.tsung.svc.cluster.local && ssh -v root@nginx.tsung.svc.cluster.local /bin/bash <<'EOT'
